#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ruborg"

begin
  Ruborg::CLI.start(ARGV)
rescue Ruborg::Error => e
  warn "Error: #{e.message}"
  exit 1
rescue Interrupt
  warn "\nInterrupted"
  exit 130
end
